# Assignment 11 - Applied Machine Learning
## Brian Colclough

### Part 1: A Priori Analysis of Alice in Wonderland


In [1]:
import nltk
from nltk.corpus import gutenberg, stopwords
import re
import pandas as pd
import numpy as np
from collections import Counter

nltk.download('gutenberg')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/briancolclough/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/briancolclough/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/briancolclough/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/briancolclough/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [2]:
sentences = gutenberg.sents('carroll-alice.txt')
print(f"Total sentences: {len(sentences)}")

print("\nFirst 5 sentences:")
for i, sent in enumerate(sentences[:5]):
    print(sent)


Total sentences: 1703

First 5 sentences:
['[', 'Alice', "'", 's', 'Adventures', 'in', 'Wonderland', 'by', 'Lewis', 'Carroll', '1865', ']']
['CHAPTER', 'I', '.']
['Down', 'the', 'Rabbit', '-', 'Hole']
['Alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of', 'sitting', 'by', 'her', 'sister', 'on', 'the', 'bank', ',', 'and', 'of', 'having', 'nothing', 'to', 'do', ':', 'once', 'or', 'twice', 'she', 'had', 'peeped', 'into', 'the', 'book', 'her', 'sister', 'was', 'reading', ',', 'but', 'it', 'had', 'no', 'pictures', 'or', 'conversations', 'in', 'it', ',', "'", 'and', 'what', 'is', 'the', 'use', 'of', 'a', 'book', ",'", 'thought', 'Alice', "'", 'without', 'pictures', 'or', 'conversation', "?'"]
['So', 'she', 'was', 'considering', 'in', 'her', 'own', 'mind', '(', 'as', 'well', 'as', 'she', 'could', ',', 'for', 'the', 'hot', 'day', 'made', 'her', 'feel', 'very', 'sleepy', 'and', 'stupid', '),', 'whether', 'the', 'pleasure', 'of', 'making', 'a', 'daisy', '-', 'chain', 'would', 'be', 'w

In [3]:
stop_words = stopwords.words('english')
print(f"Number of stop words: {len(stop_words)}")
print(f"Sample stop words: {stop_words[:20]}")


Number of stop words: 198
Sample stop words: ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [4]:
# preprocess sentences to remove stop words, symbols, and convert them to lowercase
terms_sentences = []
for terms in sentences:
    terms = [w for w in terms if w not in stop_words]
    terms = [w for w in terms if re.search(r'^[a-zA-Z]{2,}', w) is not None]
    terms = [w.lower() for w in terms]
    
    # if there are terms in the sentence, add it to the list
    if len(terms) > 0: 
        terms_sentences.append(terms)

print("Processed sentences:")
for i, sent in enumerate(terms_sentences[:5]):
    print(f"{i+1}. {sent}")


Processed sentences:
1. ['alice', 'adventures', 'wonderland', 'lewis', 'carroll']
2. ['chapter']
3. ['down', 'rabbit', 'hole']
4. ['alice', 'beginning', 'get', 'tired', 'sitting', 'sister', 'bank', 'nothing', 'twice', 'peeped', 'book', 'sister', 'reading', 'pictures', 'conversations', 'use', 'book', 'thought', 'alice', 'without', 'pictures', 'conversation']
5. ['so', 'considering', 'mind', 'well', 'could', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisy', 'chain', 'would', 'worth', 'trouble', 'getting', 'picking', 'daisies', 'suddenly', 'white', 'rabbit', 'pink', 'eyes', 'ran', 'close']


In [5]:
# get all words
all_words = [word for sentence in terms_sentences for word in sentence]
print(f"Total words: {len(all_words)}")
# find unique words
print(f"Unique words: {len(set(all_words))}")

# Show most common words
word_freq = Counter(all_words)
print(f"\nTop 20 most common words:")
for word, count in word_freq.most_common(20):
    print(f"{word}: {count}")


Total words: 13357
Unique words: 2512

Top 20 most common words:
said: 462
alice: 398
little: 128
the: 115
one: 104
know: 88
like: 85
would: 83
went: 83
could: 77
queen: 75
thought: 74
time: 71
and: 70
it: 68
see: 67
you: 66
well: 63
king: 63
turtle: 59


### Prepare transactions for A Priori Analysis

Now we'll format the data as transactions (each sentence is a transaction containing words as items).


### Run A Priori Algorithm

Using mlxtend library to find frequent word patterns (similar to FPGrowth in Weka).


In [6]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Encode transactions in one-hot format
te = TransactionEncoder()
te_ary = te.fit(terms_sentences).transform(terms_sentences)
df = pd.DataFrame(te_ary, columns=te.columns_)

print(f"Encoded transactions shape: {df.shape}")
print(f"\nFirst 5 rows:")
print(df.head())


Encoded transactions shape: (1690, 2512)

First 5 rows:
   abide   able  absence  absurd  acceptance  accident  accidentally  account  \
0  False  False    False   False       False     False         False    False   
1  False  False    False   False       False     False         False    False   
2  False  False    False   False       False     False         False    False   
3  False  False    False   False       False     False         False    False   
4  False  False    False   False       False     False         False    False   

   accounting  accounts  ...    yes  yesterday    yet    you  young   your  \
0       False     False  ...  False      False  False  False  False  False   
1       False     False  ...  False      False  False  False  False  False   
2       False     False  ...  False      False  False  False  False  False   
3       False     False  ...  False      False  False  False  False  False   
4       False     False  ...  False      False  False  False  False

In [7]:
# try different min_support values
min_supports = [0.001, 0.003, 0.005, 0.007, 0.009, 0.01, 0.02, 0.03, 0.04, 0.05]
for min_support in min_supports:
    frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)
    print(f"Min support: {min_support}, Number of frequent itemsets: {len(frequent_itemsets)}")


Min support: 0.001, Number of frequent itemsets: 25813
Min support: 0.003, Number of frequent itemsets: 1113
Min support: 0.005, Number of frequent itemsets: 548
Min support: 0.007, Number of frequent itemsets: 351
Min support: 0.009, Number of frequent itemsets: 222
Min support: 0.01, Number of frequent itemsets: 202
Min support: 0.02, Number of frequent itemsets: 63
Min support: 0.03, Number of frequent itemsets: 29
Min support: 0.04, Number of frequent itemsets: 15
Min support: 0.05, Number of frequent itemsets: 6


In [8]:
min_support = 0.01
frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)

print(f"Number of frequent itemsets: {len(frequent_itemsets)}")
print(f"\nFrequent itemsets:")
print(frequent_itemsets.sort_values('support', ascending=False).head(20))

Number of frequent itemsets: 202

Frequent itemsets:
      support       itemsets
97   0.269231         (said)
1    0.230178        (alice)
164  0.096450  (alice, said)
63   0.068639       (little)
116  0.066864          (the)
84   0.057988          (one)
139  0.048521         (went)
62   0.048521         (like)
58   0.048521         (know)
124  0.043787      (thought)
89   0.043195        (queen)
15   0.042012        (could)
147  0.041420        (would)
2    0.040237          (and)
55   0.040237           (it)
127  0.039645         (time)
149  0.039053          (you)
100  0.038462          (see)
138  0.036686         (well)
57   0.035503         (king)


In [9]:
phrases = frequent_itemsets[frequent_itemsets['itemsets'].apply(lambda x: len(x) >= 2)]
phrases = phrases.sort_values('support', ascending=False)

print(f"Number of frequent phrases of 2+ words: {len(phrases)}")
print(f"\nTop 20:\n")
for idx, row in phrases.head(20).iterrows():
    phrase = ' '.join(row['itemsets'])
    print(f"{phrase}: {row['support']:.4f}")

Number of frequent phrases of 2+ words: 52

Top 20:

alice said: 0.0964
alice thought: 0.0343
turtle mock: 0.0331
king said: 0.0254
little alice: 0.0219
like alice: 0.0195
turtle mock said: 0.0189
mock said: 0.0189
turtle said: 0.0189
you said: 0.0183
march hare: 0.0178
hatter said: 0.0172
alice could: 0.0172
little said: 0.0172
alice would: 0.0172
much alice: 0.0166
alice went: 0.0160
said queen: 0.0154
alice quite: 0.0148
would said: 0.0148


## Part 2: 2-Hidden Layer Neural Network on MNIST

In [10]:
def load_mnist(path, kind='train'):
    from numpy import fromfile, uint8
    import os
    import struct
    
    labels_path = os.path.join(path, '%s-labels-idx1-ubyte' % kind)
    images_path = os.path.join(path, '%s-images-idx3-ubyte' % kind)
    with open(labels_path, 'rb') as lbpath:
        magic, n = struct.unpack('>II', lbpath.read(8))
        labels = fromfile(lbpath, dtype=uint8)
        with open(images_path, 'rb') as imgpath:
            magic, num, rows, cols = struct.unpack(">IIII",imgpath.read(16))
            images = fromfile(imgpath, dtype=uint8).reshape(len(labels), 784)
            images = ((images / 255.) - .5) * 2
    return images, labels

X_train_mnist, y_train_mnist = load_mnist('mnist/', kind='train')
print(f'Rows= {X_train_mnist.shape[0]}, columns= {X_train_mnist.shape[1]}')

X_test_mnist, y_test_mnist = load_mnist('mnist/', kind='t10k')
print(f'Rows= {X_test_mnist.shape[0]}, columns= {X_test_mnist.shape[1]}')

Rows= 60000, columns= 784
Rows= 10000, columns= 784


In [11]:
class NeuralNetMLP(object):

    def __init__(self, n_hidden=30, epochs=100, eta=0.001, minibatch_size=1, seed=None):
        self.random = np.random.RandomState(seed)  # used to randomize weights
        self.n_hidden = n_hidden  # size of the hidden layer
        self.epochs = epochs  # number of iterations
        self.eta = eta  # learning rate
        self.minibatch_size = minibatch_size  # size of training batch - 1 would not work
        self.w_out, self.w_h1, self.w_h2 = None, None, None
    
    @staticmethod
    def onehot(_y, _n_classes):  # one hot encode the input class y
        onehot = np.zeros((_n_classes, _y.shape[0]))
        for idx, val in enumerate(_y.astype(int)):
            onehot[val, idx] = 1.0
        return onehot.T
    
    @staticmethod
    def sigmoid(_z):  # Eq 1
        return 1.0 / (1.0 + np.exp(-np.clip(_z, -250, 250)))

    def _forward(self, _X):  # Eq 2
        z_h1 = np.dot(_X, self.w_h1)
        a_h1 = self.sigmoid(z_h1)
        z_h2 = np.dot(a_h1, self.w_h2)
        a_h2 = self.sigmoid(z_h2)
        z_out = np.dot(a_h2, self.w_out)
        a_out = self.sigmoid(z_out)
        return z_h1, a_h1, z_h2, a_h2, z_out, a_out

    @staticmethod
    def compute_cost(y_enc, output):  # Eq 4
        term1 = -y_enc * (np.log(output))
        term2 = (1.0-y_enc) * np.log(1.0-output)
        cost = np.sum(term1 - term2)
        return cost

    def predict(self, _X):
        z_h1, a_h1, z_h2, a_h2, z_out, a_out = self._forward(_X)
        ypred = np.argmax(z_out, axis=1)
        return ypred

    def fit(self, _X_train, _y_train, _X_valid, _y_valid):
        import sys
        n_output = np.unique(_y_train).shape[0]  # number of class labels
        n_features = _X_train.shape[1]
        self.w_out = self.random.normal(loc=0.0, scale=0.1, size=(self.n_hidden, n_output))
        self.w_h1 = self.random.normal(loc=0.0, scale=0.1, size=(n_features, self.n_hidden))
        self.w_h2 = self.random.normal(loc=0.0, scale=0.1, size=(self.n_hidden, self.n_hidden))
        y_train_enc = self.onehot(_y_train, n_output)  # one-hot encode original y
        for ei in range(self.epochs):  # Ideally must shuffle at every epoch
            indices = np.arange(_X_train.shape[0])
            for start_idx in range(0, indices.shape[0] - self.minibatch_size + 1, self.minibatch_size):
                batch_idx = indices[start_idx:start_idx + self.minibatch_size]
                
                z_h1, a_h1, z_h2, a_h2, z_out, a_out = self._forward(_X_train[batch_idx])  # neural network model
                
                # sigmoids
                sigmoid_derivative_h1 = a_h1 * (1.0-a_h1)  # Eq 3
                sigmoid_derivative_h2 = a_h2 * (1.0-a_h2)  # Eq 3

                # deltas
                delta_out = a_out - y_train_enc[batch_idx]  # Eq 5
                delta_h2 = (np.dot(delta_out, self.w_out.T) * sigmoid_derivative_h2)  # Eq 6
                delta_h1 = (np.dot(delta_h2, self.w_h2.T) * sigmoid_derivative_h1)  # Eq 6

                # gradients
                grad_w_out = np.dot(a_h2.T, delta_out)  # Eq 7
                grad_w_h2 = np.dot(a_h1.T, delta_h2)  # Eq 8
                grad_w_h1 = np.dot(_X_train[batch_idx].T, delta_h1)  # Eq 8

                # updates
                self.w_out -= self.eta*grad_w_out  # Eq 9
                self.w_h1 -= self.eta*grad_w_h1  # Eq 9
                self.w_h2 -= self.eta*grad_w_h2  # Eq 9

            # Evaluation after each epoch during training
            z_h1, a_h1, z_h2, a_h2, z_out, a_out = self._forward(_X_train)
            cost = self.compute_cost(y_enc=y_train_enc, output=a_out)
            y_train_pred = self.predict(_X_train)  # monitoring training progress through reclassification
            y_valid_pred = self.predict(_X_valid)  # monitoring training progress through validation
            train_acc = ((np.sum(_y_train == y_train_pred)).astype(float) / _X_train.shape[0])
            valid_acc = ((np.sum(_y_valid == y_valid_pred)).astype(float) / _X_valid.shape[0])
            sys.stderr.write('\r%d/%d | Cost: %.2f ' '| Train/Valid Acc.: %.2f%%/%.2f%% '%
                (ei+1, self.epochs, cost, train_acc*100, valid_acc*100))
            sys.stderr.flush()
        return self

In [12]:
# Define and fit the neural network
nn = NeuralNetMLP(n_hidden=20, epochs=200, eta=0.0005, minibatch_size=100, seed=1)

nn.fit(X_train_mnist[:55000], y_train_mnist[:55000], X_train_mnist[55000:], y_train_mnist[55000:]) ;

200/200 | Cost: 9552.76 | Train/Valid Acc.: 97.65%/95.76%  

In [13]:
from sklearn.metrics import confusion_matrix

def get_acc(_y_test, _y_pred):
    return (np.sum(_y_test == _y_pred)).astype(float) / _y_test.shape[0]

y_pred = nn.predict(X_test_mnist)

print(f'Accuracy= {get_acc(y_test_mnist, y_pred)*100:.2f}%')
print(confusion_matrix(y_test_mnist, y_pred))

Accuracy= 94.89%
[[ 961    0    1    1    0    3    6    2    5    1]
 [   0 1105    6    2    0    1    4    3   14    0]
 [  12    2  968   12    6    0    4   10   18    0]
 [   0    0   17  958    0   11    0   10   12    2]
 [   2    0    3    1  938    0    7    4    2   25]
 [  10    1    2   27    3  818   12    4   11    4]
 [   9    4    4    0    9    8  922    0    2    0]
 [   2    8   10    9   10    1    0  979    1    8]
 [   4    2    4   12    7    6    5    9  918    7]
 [   7    5    1   13   39    3    1   10    8  922]]
